### ISSUE TITLE
Imagebuilder doesn't copy .dockerignore into the image

### ISSUE THREAD

**Issue by chancez** [openshift/imagebuilder#100]
https://github.com/openshift/imagebuilder/blob/fbd4f31c568b767447302e08fb3531b33bcbf837/dockerclient/client.go#L136

This is inconsistent with docker. I'm trying to add imagebuilder as an option in our CI to validate we work with it before getting our component into OSBS, but part of our jobs validates that there's no unstaged changes after re-generating some files (to ensure commited generated files look the same in CI as what the developer produced), but this causes issues with that since the .dockerignore is missing in the image after building.

**Comment by TomSweeneyRedHat** [comment]
How/why was this merged?  I've not looked at it at all, but it doesn't appear anyone has?

**Comment by TomSweeneyRedHat** [comment]
NVM, losing my mind in reviews.  This is an issue, not a PR.  I now crawl back under my rock.
