### ISSUE TITLE
generated image is broken

### ISSUE THREAD

**Issue by goern** [openshift/imagebuilder#11]
Hey all,
 I tried building `https://github.com/CentOS/sig-cloud-instance-images/blob/f5b919346432acc728078aa32ffb6dcf84d303a0/docker/Dockerfile` using imagebuilder. The  resulting image is broken. After a short chat with @jperrin he pointed out that there was https://github.com/docker/docker/issues/20331 which could cause this behavior. 

I was using `docker-1.10.3-26.git1ecb834.fc24.x86_64`

**Comment by goern** [comment]
I just updated to 1.10.3-50.gita612434 via fedora-updates-testing

**Comment by goern** [comment]
Still the same result, the resulting image simply containers centos-7-docker.tar.xz

**Comment by smarterclayton** [comment]
We actually use the client side logic from fsouza/go-dockerclient to accomplish this - it's using github.com/docker/docker/pkg/archive.  We just need to bump archive up to 

```
       			"ImportPath": "github.com/docker/docker/pkg/stdcopy",
       			"Comment": "v1.11.2",
       			"Rev": "b9f10c951893f9a00865890a5232e85d770c1087"
```

in the vendor.

**Comment by smarterclayton** [comment]
go-dockerclient also could stand to get bumped - Kube has not bumped yet.  Will look into that once the OpenShift rebase is complete.

**Comment by smarterclayton** [comment]
Please try PR #13 which should have fixed this.
