### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by vrothberg** [openshift/imagebuilder#114]
I am currently going through Podman's dependencies (updating the vendor.conf) trying to pin them to releases when possible and available. Some distributions, Debian in particular, are very conservative regarding go packaging as many libraries don't have any release (or no semantic versioning).

Can we tag a new release?

**Comment by rhatdan** [comment]
Sure, lets tag it 1.0 since it is in Buildah and been used for a while.

**Comment by rhatdan** [comment]
Should we add a version file to it?

**Comment by vrothberg** [comment]
> Should we add a version file to it?

Those are usually used to inject the version string during build. At the moment, my head is deep in the vendor PR for libpod but I can check after that here.

**Comment by rhatdan** [comment]
Easiest thing I can do is just tag 1.0 and create a release.  Just not sure if there is anything else I need to do to make it more formal.

**Comment by vrothberg** [comment]
I think we just need to make sure that the binary return the right version string. It shouldn't have any impact on Podman which is just vendoring.

**Comment by vrothberg** [comment]
Closing as the project is releasing now.
