### ISSUE TITLE
build failure with recent version of docker/docker

### ISSUE THREAD

**Issue by vrothberg** [openshift/imagebuilder#116]
Vendoring recent version of `docker/docker` causes build failures:
```
vendor/github.com/openshift/imagebuilder/builder.go:16:2: cannot find package "github.com/docker/docker/builder/dockerfile/command" in any of:
```

It seems that the `dockerfile` package has been refactored into a single package (no sub-packages anymore).

**Comment by TomSweeneyRedHat** [comment]
That might leave a mark.   Sigh.

**Comment by vrothberg** [comment]
It's really tough for our tools as other dependencies require higher versions of docker/docker, so you can imagine the haystack to untangle all the dependencies :-D

**Comment by TomSweeneyRedHat** [comment]
I can indeed imagine, but I really don't want to do so....

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @rhatdan ... I am trying to revive the issue.

Given the strong differences between the currently vendored version and upstream, can we copy the packages in questions into imagebuilder to resolve the conflicts? I think "forking" those packages would reflect the state.

**Comment by TomSweeneyRedHat** [comment]
I choose to hide under the table until @rhatdan weighs in....

**Comment by rhatdan** [comment]
I am fine with copying it.
