### ISSUE TITLE
Rev of glog is not checkout'able

### ISSUE THREAD

**Issue by goern** [openshift/imagebuilder#12]
looking at the Godeps it turns out that the revision of glog used cant be checked out:
```
$ git clone https://github.com/golang/glog
$ cd glog/
$ git checkout 335da9dda11408a34b64344f82e9c03779b71673
fatal: reference is not a tree: 335da9dda11408a34b64344f82e9c03779b71673
```

... or I am to newbish to Go

**Comment by smarterclayton** [comment]
You unfortunately have to fetch a remote - I forgot to document that, but it's a version of glog that we have forked at openshift/glog to support the info.Depth() command (glog doesn't accept patches).  I'll switch to glide.

**Comment by smarterclayton** [comment]
Switch into your glog directory and run:

```
git fetch openshift https://github.com/openshift/glog
```

Which should work.
