### ISSUE TITLE
wishlist: support for `--label` cmdline option

### ISSUE THREAD

**Issue by dnwe** [openshift/imagebuilder#124]
The `docker build` CLI has support for appending additional dynamic `LABEL` directives to the Dockerfile at build time and is often used to add (e.g.,) git remote / ref and other build information to the images. Currently `imagebuilder` doesn't appear to have a way of specifying these on the CLI

```
$ docker build --help

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Options:
...
--label list              Set metadata for an image
...
```

**Comment by rhatdan** [comment]
We do have support for this in Buildah. And on Podman build

**Comment by dnwe** [comment]
@rhatdan yeah I did see that [containers/buildah](https://github.com/containers/buildah) had support via [bud](https://github.com/containers/buildah/blob/master/cmd/buildah/bud.go) for doing a Dockerfile-based image build and using a `--labels` arg
