### ISSUE TITLE
Support for podman/buildah

### ISSUE THREAD

**Issue by gnufied** [openshift/imagebuilder#128]
I am trying to build images of https://github.com/openshift/kube-controller-manager-operator on my local desktop only with cri-o/podman/buildah installed and I can't build images. 

Here is the `Makefile` that is invoked by build process - https://github.com/openshift/library-go/blob/master/alpha-build-machinery/make/targets/openshift/images.mk

cc @tnozicka

**Comment by rhatdan** [comment]
Could you describe what fails?

**Comment by soltysh** [comment]
Here's the output I'm getting:
```
$ make images
imagebuilder --allow-pull -t registry.svc.ci.openshift.org/ocp/4.2:cluster-kube-controller-manager-operator -f ./Dockerfile.rhel7 .
Get http://unix.sock/images/registry.svc.ci.openshift.org/ocp/builder:golang-1.12/json: dial unix /var/run/docker.sock: connect: no such file or directory
```
I did pull both images as mentioned in the README, but that clearly did not help.

**Comment by LorbusChris** [comment]
Wrt to my question at All Systems Go, I was thinking of this issue here @rhatdan @mrguitar

**Comment by rhatdan** [comment]
This version of imagebuilder has not been ported to use Buildah.
@nalind Is this possible, or do we only have it vendored within OpenShift?

**Comment by gnufied** [comment]
Even if we fix the docker socket issue, IIRC imagebuilder uses docker's HTTP api - https://github.com/fsouza/go-dockerclient .

**Comment by LorbusChris** [comment]
> This version of imagebuilder has not been ported to use Buildah.

huh, so this repo isn't the upstream? Can we get that vendored version on a branch in this repo?

**Comment by nalind** [comment]
So far as I know, this is the home repository for imagebuilder.

The repository includes three things: a library that can parse Dockerfiles and use an object that implements its `Executor` interface to perform a build (that's `github.com/openshift/imagebuilder`), an implementation of `Executor` that uses `github.com/fsouza/go-dockerclient` to do the work with the help of a dockerd daemon (that's `github.com/openshift/imagebuilder/dockerclient`), and the CLI tool that pairs them together (that's `github.com/openshift/imagebuilder/cmd/imagebuilder`).

The `buildah` libraries provide an implementation of `Executor` that its CLI, and podman's, combine with imagebuilder's main library to allow them to build images using Dockerfiles.  While I think we could graft that into the imagebuilder CLI (give or take a couple of features), doing so would add a lot of dependencies (ballpark it growing from 14MB to about 35MB), all of them Linux-specific.

I like the idea of an `Executor` that would use varlink, though from https://github.com/containers/libpod/blob/master/API.md it's not clear to me if it provides all of the functionality that `Executor` would need to be able to use.

**Comment by LorbusChris** [comment]
IIUC that means the imagebuilder CLI does not work with buildah, but there is some way to do a buildah build with imagebuilder programmatically?
