### ISSUE TITLE
COPY --from doesn't fail when source file doesn't exist

### ISSUE THREAD

**Issue by rcerven** [openshift/imagebuilder#137]
when copying file from previous stage
via COPY --from=previous_stage
build doesn't fail on COPY command when source file doesn't exist

--> COPY --from=stage1 /opt/non-existent  /file_from_stage1
--> RUN cat /file_from_stage1
cat: /file_from_stage1: No such file or directory
running 'cat /file_from_stage1' failed with exit code 1

**Comment by nalind** [comment]
This should be fixed by #148, but I didn't phrase it right for that to happen automatically when it was merged.  Closing.
