### ISSUE TITLE
imagebuilder fails with `unauthorized: authentication required` when it should not (proper auths in ~/.docker/config.json)

### ISSUE THREAD

**Issue by sallyom** [openshift/imagebuilder#144]
These works (several repositories, [here's an example](https://github.com/openshift/cluster-config-operator) ):
`buildah bud -f Dockerfile.rhel7 -t myimage:local .`
`docker build -f Dockerfile.rhel7 -t myimage:local .`

This fails:
`imagebuilder --allow-pull -t myimage:local -f ./Dockerfile.rhel7 .`
Fails with:
```console
$ imagebuilder --allow-pull -t quay.io/sallyom/myimage:local -f ./Dockerfile.rhel7 .
--> Image registry.svc.ci.openshift.org/ocp/builder:golang-1.12 was not found, pulling ...
unable to pull image (from: registry.svc.ci.openshift.org/ocp/builder, tag: golang-1.12): unauthorized: authentication required
```
Workaround is to pre-pull with docker whatever you need:
`docker pull registry.svc.ci.openshift.org/ocp/4.2:base`
`docker pull registry.svc.ci.openshift.org/ocp/builder:golang-1.12`
(has to be in docker storage rather than buildah,podman)

**Comment by aojea** [comment]
/reopen
if this is not going to be fixed, is not better to move away from imagebuilder and use another option that works?
