### ISSUE TITLE
Incorrect output for '%' in strings

### ISSUE THREAD

**Issue by twaugh** [openshift/imagebuilder#15]
This Dockerfile:
```
FROM busybox
RUN stat -c %u /
```

produces this output:
```
--> FROM busybox
--> RUN stat -c %!u(MISSING) /
0
--> Committing changes ...
--> Done
```

It is only the output of which instruction is to be run that is incorrect. The correct instruction is run.

**Comment by smarterclayton** [comment]
Ah, this is Go rules.  Need to escape it for printf.
