### ISSUE TITLE
Regression in ENV expansion

### ISSUE THREAD

**Issue by yselkowitz** [openshift/imagebuilder#173]
There has been a recent regression in expansion of ENV since 1.1.6.  Test case:
``` Dockerfile
FROM registry.redhat.io/ubi8

ENV FOO_DIR=/opt/foo
ENV PATH=$FOO_DIR/bin:$PATH

RUN ls -l
```
With 1.1.6 or earlier, this works as expected.  With git master it falis:
```
--> RUN ls -l
/bin/sh: ls: command not found
```
My guess is https://github.com/openshift/imagebuilder/pull/169 may be the culprit but I haven't bisected it.

(The real-life case was https://github.com/kube-reporting/hadoop fwiw.)

**Comment by nalind** [comment]
Yup, it broke at #169.

**Comment by nalind** [comment]
:facepalm:  Okay, I think #174 will fix it.
