### ISSUE TITLE
ADD should unpack archives

### ISSUE THREAD

**Issue by jpkrohling** [openshift/imagebuilder#194]
My Dockerfile has a "ADD" directive, which should unpack the tar.gz files in the image and it works fine for a "regular" build. But if I change the container.yaml to use `image_build_method: imagebuilder` instead, the "ADD" directive copies the tar.gz without unpacking it.

Reproducer:

container.yaml:
```yaml
compose:
  pulp_repos: true
image_build_method: imagebuilder
platforms:
  only:
    - x86_64
    - s390x
    - ppc64le
```

Dockerfile
```Dockerfile
FROM registry.redhat.io/ubi8/ubi
ADD *.tar.gz /packages/
COPY setup.sh /
RUN /setup.sh
```

setup.sh
```bash
echo "LIST PACKAGES:"
ls -l packages
```

It will list tar.gz files. Removing the `image_build_method` node from `container.yaml` will cause directories to be listed.

Reference: https://docs.docker.com/engine/reference/builder/#add

> If < src > is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed. When a directory is copied or unpacked, it has the same behavior as tar -x, the result is the union of:
>
>    1. Whatever existed at the destination path and
>    2. The contents of the source tree, with conflicts resolved in favor of “2.” on a file-by-file basis.

**Comment by nalind** [comment]
This should have been fixed in #176 and #179, which were part of the 1.1.8 release.  Which version are you running?

**Comment by jpkrohling** [comment]
Whatever version is/was available in OSBS as of last week.

**Comment by jpkrohling** [comment]
Not sure this is the trigger, but it was a multi-stage build...

**Comment by jpkrohling** [comment]
If it help, here's one build that failed because of that: http://download.eng.bos.redhat.com/brewroot/work/tasks/368/38430368/x86_64.log

**Comment by nalind** [comment]
Hmm, it looks like the previous fixes didn't take into account cases where the source was a globbing pattern.  If you know the filenames in advance, listing them explicitly should work around that until we get this fixed properly.
