### ISSUE TITLE
go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.1 failed

### ISSUE THREAD

**Issue by zhujian7** [openshift/imagebuilder#199]
Run `go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.1` failed in the latest version ubuntu, GitHub action's virtual environment, and [the GitHub action ubuntu was updated recently](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210803.0), there are no problems before its update.

Failed information：
```
Error: ../../../pkg/mod/github.com/containers/storage@v1.33.2/pkg/idtools/idtools_supported.go:13:10: fatal error: shadow/subid.h: No such file or directory
   13 | #include <shadow/subid.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
Error: Process completed with exit code 2.
```
I want to know where can I get the `shadow/subid.h` file, and how？ very appreciated If anyone can give me some hints

**Comment by rhatdan** [comment]
It is in the latest shadow-utils package. shadow-utils-4.9
You can eliminate the need to compile it with the `no_libsubid` build tag

**Comment by nalind** [comment]
This should be fixed in containers/storage with https://github.com/containers/storage/pull/986.  v1.2.1 didn't use Go modules, so I'm guessing Go defaulted to using the latest tagged release of the dependency.  The new latest version incorporates that change, so this should be fixed now.
