### ISSUE TITLE
Does imagebuilder support concurrent building?

### ISSUE THREAD

**Issue by msugakov** [openshift/imagebuilder#201]
Docker [BuildKit released last year](https://www.docker.com/blog/advanced-dockerfiles-faster-builds-and-smaller-images-using-buildkit-and-multistage-builds/) figures out a graph of dependencies between stages in Dockerfile and parallelizes builds where possible.
While there's not a lot of information how it does that, I see considerable speed-up when building certain images with BuildKit enabled.
Does imagebuilder support anything like that already? How do configure the degree of parallelism?
Thanks!

**Comment by nalind** [comment]
It doesn't currently support that.  In principle I think it could.
