### ISSUE TITLE
BUG: labels following missing line-continuation character are ignored

### ISSUE THREAD

**Issue by ben-alkov** [openshift/imagebuilder#235]
e.g.

```dockerfile
LABEL name="tech-preview/vm-launcher" \
      version="v0.0.1" \
      release="10"
      summary="Hosts VMs" \
```

does NOT fail as expected, but simply ignores all labels following `release`.

podman fails as expected.

**Comment by nalind** [comment]
When I try to build this Dockerfile with the current version:
```Dockerfile
LABEL name="tech-preview/vm-launcher" \
      version="v0.0.1" \
      release="10"
      summary="Hosts VMs" \
```
the build completes, but I get a `--> warning: Unknown instruction: SUMMARY="HOSTS` warning in the output.  If I build with the `-ignore-unrecognized-instructions=false` flag, the build errors out.  Are you seeing different behavior?  Are you using a different release of `imagebuilder`?

**Comment by ben-alkov** [comment]
Unfortunately, I'm not able to even build a reproducer right now, but AFAIK:

> the build completes, but I get a --> warning: Unknown instruction: SUMMARY="HOSTS warning in the output

Our builds complete; build owners are probably simply ignoring that warning

> If I build with the -ignore-unrecognized-instructions=false flag, the build errors out. Are you seeing different behavior?

We *always* build with `--ignore-unrecognized-instructions=true`

> Are you using a different release of imagebuilder?

1.2.1

**Comment by nalind** [comment]
> > If I build with the -ignore-unrecognized-instructions=false flag, the build errors out. Are you seeing different behavior?
> 
> We _always_ build with `--ignore-unrecognized-instructions=true`

I am sorely tempted to try to change the default for that from `true` to `false`.
