### ISSUE TITLE
imageProgressWriter doesn't propagate docker errors under certain conditions

### ISSUE THREAD

**Issue by mmilata** [openshift/imagebuilder#32]
The issue is that `imageProgressWriter` can be used in two ways, by calling `ReadFrom` or by calling `Write` (possibly multiple times). Both go-dockerclient and unit tests pass the writer to `io.Copy` which uses the `ReadFrom` method. However when I wrap imageProgressWriter in an `io.MultiWriter` the `Write` method is used which results in slightly different behavior. For example when the decoded JSON object contains `error` key, `ReadFrom` returns the error immediately but `Write` returns it on the next invocation which may never happen.

For openshift/origin#12407 I have an implementation of `Write` that does not use `io.Pipe`/goroutine but it's ugly and does a lot of unnecessary copying: https://github.com/mmilata/origin/blob/25a5c910d1afb87a0f8b6266954a72ee7eca4ec8/pkg/build/builder/dockerutil.go#L253

To reproduce:
```
diff --git a/imageprogress/progress_test.go b/imageprogress/progress_test.go
index 2438d80..d959f5f 100644
--- a/imageprogress/progress_test.go
+++ b/imageprogress/progress_test.go
@@ -79,7 +79,7 @@ func TestReports(t *testing.T) {
                        },
                )
                w.(*imageProgressWriter).stableThreshhold = 0
-               _, err := io.Copy(w, pipeIn)
+               _, err := io.Copy(io.MultiWriter(w), pipeIn)
                if err != nil {
                        if !test.errExpected {
                                t.Errorf("%s: unexpected: %v", test.name, err)
@@ -115,7 +115,7 @@ func TestErrorOnCopy(t *testing.T) {
        w := newWriter(func(r report) {}, func(a, b report) bool { return true })
 
        // Ensure that the error is propagated to the copy
-       _, err := io.Copy(w, genIn)
+       _, err := io.Copy(io.MultiWriter(w), genIn)
        if err == nil {
                t.Errorf("Did not get an error when copying to writer")
        }
```

**Comment by smarterclayton** [comment]
Since this was just a copy of @csrwng's original code, we should just port the changes back.
