### ISSUE TITLE
Plans re: containers/image and containers/storage support?

### ISSUE THREAD

**Issue by nalind** [openshift/imagebuilder#33]
Hi!  I've spent a bit of time recently working on a tool (currently http://github.com/nalind/buildah - be kind, it's early days) for building OCI images using https://github.com/containers/storage and https://github.com/containers/image, and before I go too far down the implementation road, I wanted to ask if you think if these things which `buildah` is looking to do would make more sense to implement as functions of `imagebuilder`:
* using `containers/storage` for directly manipulating a working container and `containers/image` for importing and committing images, as an alternative to or in place of talking to `dockerd`
* implementing instructions that would be found in a Dockerfile or equivalent as CLI tools that can be called from a command prompt or as part of a shell script, storing state in locations that the storage library offers, eventually allowing the image building process to be a shell interpreting a script instead of a single tool interpreting a Dockerfile

I expect the first bullet point could make things pretty messy, since it would likely require entirely different code paths, and the second may be completely out of scope for `imagebuilder`, but I'd like to know what the maintainers think.

**Comment by smarterclayton** [comment]
The intent for this originally was to allow different execution engines.  I'd be in favor of adding a `direct` which used storage / image and similar calls to isolate the environment.

**Comment by smarterclayton** [comment]
Now that buildah exists I'm going to close this.  We may still add a mode which shells out to buildah for use inside of kubernetes, but that could also exist in another project.
