### ISSUE TITLE
`go get` fails to compile

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/imagebuilder#42]
With `golang-1.7.3-0.2.el7.x86_64`:

```
failed: [172.18.13.178] (item=github.com/openshift/imagebuilder/cmd/imagebuilder) => {
    "changed": true, 
    "cmd": [
        "go", 
        "get", 
        "github.com/openshift/imagebuilder/cmd/imagebuilder"
    ], 
    "delta": "0:00:33.606174", 
    "end": "2017-04-13 14:49:42.627503", 
    "failed": true, 
    "item": "github.com/openshift/imagebuilder/cmd/imagebuilder", 
    "rc": 2, 
    "start": "2017-04-13 14:49:09.021329", 
    "stderr": [
        "# github.com/openshift/imagebuilder", 
        "/data/src/github.com/openshift/imagebuilder/evaluator.go:15: undefined: parser.SetEscapeToken", 
        "/data/src/github.com/openshift/imagebuilder/evaluator.go:18: too many arguments in call to parser.Parse", 
        "/data/src/github.com/openshift/imagebuilder/evaluator.go:18: cannot use *parser.Result as type *parser.Node in return argument"
    ], 
    "stdout": [], 
    "warnings": []
}
```

[here](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/57/consoleFull#199821095558b6e51eb7608a5981914356)

/cc @smarterclayton

**Comment by stevekuznetsov** [comment]
Last successful run [here](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/54/consoleFull) also with `golang-1.7.3-0.2.el7.x86_64`:

```
changed: [172.18.6.114] => (item=github.com/openshift/imagebuilder/cmd/imagebuilder) => {
    "changed": true, 
    "cmd": [
        "go", 
        "get", 
        "github.com/openshift/imagebuilder/cmd/imagebuilder"
    ], 
    "delta": "0:00:37.391519", 
    "end": "2017-04-12 20:11:47.225200", 
    "item": "github.com/openshift/imagebuilder/cmd/imagebuilder", 
    "rc": 0, 
    "start": "2017-04-12 20:11:09.833681", 
    "stderr": [], 
    "stdout": [], 
    "warnings": []
}
```

**Comment by smarterclayton** [comment]
Weird, wfm right now.

**Comment by smarterclayton** [comment]
It failed on the hub too, but now it passes.  I think it was a flake with the image being served by Google.

**Comment by smarterclayton** [comment]
So hub continues to fail, local builds continue to work.  Might be a glitch in centos, or a glitch in the docker filesystem driver (which seems unlikely, but is a concrete difference between hub, rhel, and my box).

**Comment by stevekuznetsov** [comment]
Yeah, the job (on RHEL) is continuing to fail. We're pulling Go from the CentOS repo.

**Comment by stevekuznetsov** [comment]
It seems to be pulling in the latest `docker/docker`, which has https://github.com/docker/docker/commit/64c4c1c3d5e0fe364d83db5a8dc99a24fd121754#diff-a70e690b6dc1bcdbae36a5f54c868bbeL85 and breaks your code.

**Comment by smarterclayton** [comment]
We weren't vendoring a specific directory.
