### ISSUE TITLE
Dockerfile reference

### ISSUE THREAD

**Issue by olivierGATSNCF** [openshift/imagebuilder#64]
Hi,
I am in the situation where I have to do docker builds in docker containers. Your solution through buildah interests me and would avoid the docker sock mapping.
What dockerfile instructions are supported?
I did not find any information in the OCI specifications.

Is there a corresponding docker version from which dockerfile instructions are compatible with imagebuilder usage?

**Comment by rhatdan** [comment]
Do you want to ask this question here or over in Buildah?

https://github.com/projectatomic/buildah

I think all current Dockerfile functions except for chain builds are now implemented.  Chain builds are implemeneted in imagebuilder, but not in Buildah yet.  There is an Open PR working through the issues.
