### ISSUE TITLE
Whiteout files not supported

### ISSUE THREAD

**Issue by sosiouxme** [openshift/imagebuilder#75]
When a whiteout file is created it should result in a file being removed from the resulting fs. For example:

```
$ cd $(mktemp -d)
$ echo "repo contents" > foo.repo
$ touch .wh.foo.repo
$ cat <<DF > Dockerfile
FROM fedora:28

ADD foo.repo /opt/foo.repo
RUN cat /opt/foo.repo
ADD .wh.foo.repo /opt/
RUN cat /opt/foo.repo
DF
$ docker build .
Sending build context to Docker daemon 3.584 kB
Step 1/5 : FROM fedora:28
 ---> cc510acfcd70
Step 2/5 : ADD foo.repo /opt/foo.repo
 ---> Using cache
 ---> fe5009f4a07d
Step 3/5 : RUN cat /opt/foo.repo
 ---> Using cache
 ---> 282b0d8f9bd2
Step 4/5 : ADD .wh.foo.repo /opt/
 ---> Using cache
 ---> 6d064295b23e
Step 5/5 : RUN cat /opt/foo.repo
 ---> Running in 9a82b576101a
cat: /opt/foo.repo: No such file or directory
The command '/bin/sh -c cat /opt/foo.repo' returned a non-zero code: 1
```

The command fails because the whiteout file takes effect. With imagebuilder in contrast:

```
$ imagebuilder -t foo .
--> FROM fedora:28 as 0
--> ADD foo.repo /opt/foo.repo
--> RUN cat /opt/foo.repo
repo contents
--> ADD .wh.foo.repo /opt/
--> RUN cat /opt/foo.repo
repo contents
--> Committing changes to foo ...
--> Done
[tmp.grxZVQQgyo] $ docker run foo ls -la /opt/
total 4
drwxr-xr-x. 1 root root 22 May 24 18:03 .
drwxr-xr-x. 1 root root  6 May 24 18:04 ..
-rw-rw-r--. 1 root root 14 May 24 17:21 foo.repo
```

The file remains. This is not really a difference in docker build, it's simply that whiteout files act on previous layers and with imagebuilder the whiteout file is placed in the same layer as the file it was intended to affect.

It's arguable whether we really want imagebuilder to emulate this somehow, but it would really simplify this use case.

**Comment by nalind** [comment]
Different storage drivers have different ways to handle removal of contents that were present in a lower layer.  What's the intended result of creating a `.wh.foo.repo` file instead of just deleting `foo.repo`?

**Comment by sosiouxme** [comment]
Fair point, it seemed like a hack anyway.

Deleting a file (let's assume with `RUN rm file`) requires that the current USER have permission to delete the file, so it's not a simple inverse of ADD. In our case we're wanting to automate the addition of a yum repo file at the beginning of the Dockerfile and then removing it at the end (to supply a build repo written on the fly). This means we have to determine what the USER is supposed to be at the end and switch it like so:

```
USER root
RUN rm /etc/yum.repos.d/foo.repo
USER previous_user
```

And that assumes rm is even present -- if your base image is scratch that will break (so would using yum, but  this is automation, it doesn't know if the repo will be needed or not).

As an alternative, we can ADD an empty file to overwrite it at the end, but then you have a useless empty file to confuse people. Ideally, we could mount the file as a volume during the build so it's never present in the container; but the repo file is generated in a container fs, so mounting it into the build container is complicated.

It would be great if there were a `REMOVE` instruction or `ADD --remove` option for removing files, or some other way for imagebuilder to facilitate this.

But if nothing else, this issue just serves as notice that the whiteout file hack works differently here.

**Comment by smarterclayton** [comment]
I think docker actually standardizes on the whiteout format inside the tar.  The question is whether we can safely do that via the invocation of the command.  You'd get into some interesting cases where whiteout doesn't have the same behavior.
