### ISSUE TITLE
COPY path_without_slash . when working dir is root does not work

### ISSUE THREAD

**Issue by smarterclayton** [openshift/imagebuilder#79]
```
FROM x
WORKDIR /
COPY directory .
```

where directory contains `/etc/file` does not put `file` into `/etc`, but into `/directory/etc/file`.

Broke openshift ansible.

**Comment by sosiouxme** [comment]
As a workaround does either of these work:

    COPY directory/ .
    COPY directory/* ./

**Comment by smarterclayton** [comment]
Yes, both of those are valid workarounds.  I found a few other small edge cases, but in general the end result of this will be even more testing and debug around COPY (which continues to be the gift that keeps on giving).
