### ISSUE TITLE
directory not created with WORKDIR and VOLUME

### ISSUE THREAD

**Issue by sosiouxme** [openshift/imagebuilder#87]
```
$ cat Dockerfile

FROM centos:7
WORKDIR /foo
VOLUME  [ "/foo" ]
RUN echo

$ imagebuilder .
--> FROM centos:7 as 0
--> WORKDIR /foo
--> VOLUME  [ "/foo" ]
--> RUN echo
API error (404): {"message":"lstat /var/lib/docker/overlay2/6b7c9551518e64992927f58da362b38949eddbb602f5eea6e15a9278be278bdb/merged/foo/: no such file or directory"}
```

You will also get a different error without the `VOLUME` line:

`/bin/sh: line 0: cd: /foo: No such file or directory`

Docker creates the dir implicitly.

The workaround is to `RUN mkdir /foo` before using it as a volume or workdir.

**Comment by sosiouxme** [comment]
@smarterclayton noticed this one because OSBS adds a `RUN rm repos` line at the end of every build.

**Comment by sosiouxme** [comment]
@smarterclayton just to bump this one...

**Comment by sosiouxme** [comment]
> Workdir is supposed to implicitly create a dir if you have a run statement.
>

Yes... the problem is imagebuilder apparently doesn't.

**Comment by smarterclayton** [comment]
A similar fix could work yes.

**Comment by sosiouxme** [comment]
@smarterclayton just bumping issues in this repo... I haven't had a chance to look at them either :(

**Comment by sosiouxme** [comment]
https://github.com/openshift/imagebuilder/pull/113

**Comment by sosiouxme** [comment]
Fixed!
