### ISSUE TITLE
imagebuilder waits for child processes to complete; docker build doesn't

### ISSUE THREAD

**Issue by sosiouxme** [openshift/imagebuilder#88]
With a Dockerfile that runs a simple bash script which spawns a child, I found that docker build would finish and kill the build container as soon as the script finished, while imagebuilder would wait for the child to finish:

```
$ git clone https://github.com/sosiouxme/scratch -b 20180720-subprocess-wait

$ docker build --no-cache scratch
Sending build context to Docker daemon 72.19 kB
Step 1/3 : FROM fedora:28
 ---> 75aeb7f897fd
Step 2/3 : ADD script.sh /usr/bin/
 ---> 12ff6dbff87c
Removing intermediate container 64a93a2cbce6
Step 3/3 : RUN script.sh
 ---> Running in fae77c14c89b
parent done
 ---> ab6d22ef095c
Removing intermediate container fae77c14c89b
Successfully built ab6d22ef095c

$ imagebuilder scratch
--> FROM fedora:28 as 0
--> ADD script.sh /usr/bin/
--> RUN script.sh
parent done
child done
--> Committing changes ...
--> Done
```

This might not seem like a big problem but it is the source of my hung builds.

In the logging-kibana build, as part of the build, the node process starts up a daemon. This is because it runs some slow optimize/cache code up front, to store the result in the image so that it doesn't have to be done at runtime. But it doesn't properly kill the daemon so imagebuilder waits forever for it to finish.

Arguably this is just a badly-behaving build, just like if it started an infinite loop in the foreground. But infinite loops are more evident than forgotten children. If folks are testing their builds with docker they will not consider this a problem and imagebuilder will seem broken. And in our production OSBS, at least, the build never completes, blocking any other attempts at building until an admin can cancel it.

**Comment by smarterclayton** [comment]
Interesting, I'll have to look at why this is.  It's probably how we're invoking the nested shell script - I might need to be running exec.

**Comment by smarterclayton** [comment]
Ok, it's because the container has a PID 1, we use docker exec to `RUN`, and the process you spawn stays around running in the container.  We need to stop the container at the end of the build (probably hard stop, since i don't see a use case for not doing that).

**Comment by smarterclayton** [comment]
Fix up, please try it out.

**Comment by twaugh** [comment]
FWIW 'buildah bud' seems to act in the same way as docker.
