### ISSUE TITLE
ADD doesn't expand archives

### ISSUE THREAD

**Issue by sosiouxme** [openshift/imagebuilder#99]
There's this fun Docker behavior where ADD (but not COPY!) will expand a tarball instead of just copying it into place as-is. 

[If \<src\> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed. ... Whether a file is identified as a recognized compression format or not is done solely based on the contents of the file, not the name of the file. ](https://docs.docker.com/engine/reference/builder/#add)

imagebuilder doesn't do that. This would be useful to expand source archives from lookaside in OSBS. You can work around it with `RUN tar fx` or whatever but it's one more difference to have to account for.

```
🐚 cd $(mktemp -d)
[tmp.aqbI4PmaDS] 🐚 touch foo 
[tmp.aqbI4PmaDS] 🐚 tar fc foo.tar foo
[tmp.aqbI4PmaDS] 🐚 cat <<DF > Dockerfile
> FROM fedora:28
> WORKDIR /tmp
> ADD foo.tar .
> RUN ls | grep foo
> DF
[tmp.aqbI4PmaDS] 🐚 imagebuilder .
--> FROM fedora:28 as 0
--> WORKDIR /tmp
--> ADD foo.tar .
--> RUN ls | grep foo
foo.tar
--> Committing changes ...
--> Done
[tmp.aqbI4PmaDS] 🐚 
[tmp.aqbI4PmaDS] 🐚 
[tmp.aqbI4PmaDS] 🐚 docker build .
Sending build context to Docker daemon 13.31 kB
Step 1/4 : FROM fedora:28
 ---> 75aeb7f897fd
Step 2/4 : WORKDIR /tmp
 ---> Using cache
 ---> 41c3743a8378
Step 3/4 : ADD foo.tar .
 ---> 329f459cf92a
Removing intermediate container 80b097ebbd16
Step 4/4 : RUN ls | grep foo
 ---> Running in 34e030016475
foo
 ---> c5ae75b6e86b
Removing intermediate container 34e030016475
Successfully built c5ae75b6e86b
```

**Comment by twaugh** [comment]
FWIW buildah seems to handle this the same way docker does:
```
STEP 4: RUN ls | grep foo
foo
```
